// <auto-generated />
using System;
using MVW_EF_Razor_demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVW_EF_Razor_demo.Migrations
{
    [DbContext(typeof(RatingSystemContext))]
    partial class RatingSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.MatchGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfPlay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MatchGames");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RatedPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatedPlayerId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MatchGameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchGameId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("MatchGameRating", b =>
                {
                    b.Property<int>("MatchGamesId")
                        .HasColumnType("int");

                    b.Property<int>("RatingsId")
                        .HasColumnType("int");

                    b.HasKey("MatchGamesId", "RatingsId");

                    b.HasIndex("RatingsId");

                    b.ToTable("MatchGameRating");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Player", b =>
                {
                    b.HasOne("MVW_EF_Razor_demo.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Rating", b =>
                {
                    b.HasOne("MVW_EF_Razor_demo.Models.Player", "RatedPlayer")
                        .WithMany()
                        .HasForeignKey("RatedPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RatedPlayer");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Team", b =>
                {
                    b.HasOne("MVW_EF_Razor_demo.Models.MatchGame", null)
                        .WithMany("Teams")
                        .HasForeignKey("MatchGameId");
                });

            modelBuilder.Entity("MatchGameRating", b =>
                {
                    b.HasOne("MVW_EF_Razor_demo.Models.MatchGame", null)
                        .WithMany()
                        .HasForeignKey("MatchGamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVW_EF_Razor_demo.Models.Rating", null)
                        .WithMany()
                        .HasForeignKey("RatingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.MatchGame", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("MVW_EF_Razor_demo.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
